### ISSUE TITLE
The computation of F1 is wrong thoroughly!

### ISSUE THREAD

**Issue by TianleiWang** [niamhbelton/FewSOME#2]
In my opinion, the computation of F1 is wrong.

The output with "outputs > thres" are first set to be 1. Then, these "1" are also used for the following "outputs <= thres".

To my complete shock, the threshold is chosen by "the outputs of testing" by 10% proportion. In this way, your testing accuracy is fixed and can be predicted in advance to be 90% (F1 can be a bit biased, but it is also fixed and can be predicted in advance). Then, due to the above fault, your F1 float around 90%, as shown in your paper.

Beacause your test dataset including anomalies, 90% may be not very accurate and even higher. For example, CIFAR10 testing cosists of 10% targets and 90% anomalies. Targets always have lower/higher distances/scores than anomalies due to your model trained only using targets. Ideally, you get 100% accuracy by your threshold setting.

But, the threshold is also a part of your model. It can't be derived from the testing. In other words, your high accuracy is caused by the testing information leakage.

What you do will mislead the people who will work in this field in the future.

**Comment by niamhbelton** [comment]
Note that our method of calculating the F1 score is explicitly **outlined in the paper** and our **code is open-source** so it is not fair to say that this will mislead people in future. Future methods can use the same method for choosing a threshold when comparing their method to FewSOME **OR** they can implement the FewSOME code with their own method for choosing a threshold.

Note that **our goal was to simply compare methods using F1 score**, which we achieved by choosing a method for calculating the threshold and **ensuring that the same method is applied across all models** so that **no competing method has an unfair advantage.** 

We ensure that we give an accurate representation of FewSOME’s performance by **reporting the AUC on all experiments**. F1 and balanced accuracy are included as complimentary metrics. What you are describing is the widely and well-known limitation of calculating the F1 score. This limitation is why we primarily use AUC.

I’m closing this issue as it is not a Github/code issue. The code is implemented correctly as described in the paper.
